[package]
name = "rust_frp_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
rust_frp_util = { path = "../rust_frp_util" }
rust_frp_net = { path = "../rust_frp_net" }
rust_frp_config = { path = "../rust_frp_config" }
rust_frp_auth = { path = "../rust_frp_auth" }
