[package]
name = "rust_frp_net"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio-openssl = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
rust_frp_util = { path = "../rust_frp_util" }
openssl = { version = "0.10", features = ["vendored"] }
